-- Criar um grafico de mapa mostando a soma dos votos dos canditados a presidência

--Query usada no Power BI:
select
 TP_AGREMIACAO,
 NR_PARTIDO,
 SG_PARTIDO,
 NM_COLIGACAO,
 DS_COMPOSICAO_COLIGACAO,
 DS_CARGO,
 NR_CANDIDATO,
 NM_CANDIDATO,
 'BRASIL' PAIS,
 SG_UF,
 NM_MUNICIPIO,
 SUM(CAST(QT_VOTOS_NOMINAIS AS INT)) QT_VOTOS_NOMINAIS,
 SUM(CAST(QT_VOTOS_NOMINAIS_VALIDOS AS INT)) QT_VOTOS_NOMINAIS_VALIDOS
from 
 dbo.votacao_candidato_munzona_2022_BRASIL
where
 CD_CARGO = 1 -- PRESIDENTE
GROUP BY 
 TP_AGREMIACAO,
 NR_PARTIDO,
 SG_PARTIDO,
 NM_COLIGACAO,
 DS_COMPOSICAO_COLIGACAO,
 DS_CARGO,
 NR_CANDIDATO,
 NM_CANDIDATO,
 SG_UF,
 NM_MUNICIPIO